spring:
  application:
    name: test-service

server:
  port: 9091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
  instance:
    hostname: localhost