spring:
  application:
    name: unit-conversion-service

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
  instance:
    hostname: localhost