insert into CONVERSION_OBJECT(FROM_UNIT,TO_UNIT,CONVERSION_FACTOR,PORT) values('m','mm',1000,0);
insert into CONVERSION_OBJECT(FROM_UNIT,TO_UNIT,CONVERSION_FACTOR,PORT) values('m','dm',10,0);
insert into CONVERSION_OBJECT(FROM_UNIT,TO_UNIT,CONVERSION_FACTOR,PORT) values('m','cm',100,0);